#!/bin/sh
set -e

URL=$1
DIR=$2

if [ "$URL" = "" ]; then
	echo "You must specify a git URL to clone."
	exit 1
fi
if [ "$DIR" = "" ]; then
	DIR=${URL##*/}
	DIR=${DIR%.git}
fi

mkdir $DIR
cd $DIR
git clone --mirror $URL .git
(cd .git && git fast-export --all --export-marks=../.git.marks) | \
	fossil import --git --export-marks=.fossil.marks .repo.fossil
fossil settings -R .repo.fossil allow-symlinks on
fossil settings -R .repo.fossil editor vim
fossil settings -R .repo.fossil mv-rm-files hard
fossil settings -R .repo.fossil autosync off
fossil open .repo.fossil

